### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by dkratzert** [cx-asap/CX-ASAP#11]
Hi,
you have an interesting project. I just want to point you to some other projects that could be of interest for you, but you probably know them already:

* An extremely fast CIF parser and editor. it has also many extra crystallographic features
https://gemmi.readthedocs.io/en/latest/

* A node editor to run jobs like editing and refinement on a remote computer
https://github.com/JLuebben/Floppy

* A SHELX parser and editor
https://github.com/dkratzert/ShelXFile

**Comment by amyjaynethompson** [comment]
Hi,

Thanks for the interest in CX-ASAP and for linking these tools - it is much appreciated. I definitely wish I'd found the SHELX parser and editor before writing this package!

I will keep them in mind for future updates and improvements :)
