### ISSUE TITLE
Update Tests

### ISSUE THREAD

**Issue by amyjaynethompson** [cx-asap/CX-ASAP#19]
Tests need updating - not urgent, but will be nice to have new pull requests not all fail :) 

test_rotation_planes - think ref cell now needs angles added and check with the corrected code what the output angle should be 
test_yamls - need to add new hbond param to this 

To run the tests locally cd to the folder and run python pytest name_of_test_file.py 

Probably easiest to make a branch based off dev (dev_test_update or something), and then submit a pull request to dev

**Comment by jkclegg** [comment]
I think this is done now!
