### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by idho-cryst** [cx-asap/CX-ASAP#34]
Hi team, 
I am very raw at this and have am handcuffed of having to apply for admin rights for short periods. I was installing and came to this error. 

![image](https://github.com/user-attachments/assets/cd0b81b9-34bb-483a-ab9b-a361de4ac688)

This may be very easily solved but any help would be appreciated.
Thanks,

**Comment by jkclegg** [comment]
I think this is an issue from a legacy requirements.txt file and appears to be numpy 1.19.4 no installing with python3.12. Version 2.0.1 of numpy is now required. We have updated the requirements list. Please pull the latest version of the code and try again :)
